title: Крещение поворотом
description: Клинические разборы реальных случаев из практики скорой медицинской помощи, справочные материалы, интерактивные тренажеры, тесты, задачи.
theme: jekyll-theme-primer
lang: ru-RU
